In [1]:
import pandas as pd

#### Formatting `data-stopfake.csv`

In [2]:
# load and look through data

df = pd.read_csv('./data-collection/data-stopfake.csv')
df

      page                                               text
0        1  Відеофейк: Український військовий підірвався п...
1        1  Фейк: Росіянин шкодує, що отримав громадянство...
2        1  Фейк: Розслідування Bellingcat довело, що Єрма...
3        1  Фейк: Український банк пригрозив «ухилянтам» о...
4        1   Фейк: Українські військові залишаться без виплат
...    ...                                                ...
2989   299  Фотофейк: український прикордонник на КПП “Ста...
2990   300  Фейк: Євросоюз прагне поліпшити відносини з Ро...
2991   300  Фейк: Громадян України масово депортують з ЄС ...
2992   300  Фейк: В Україні відклали на рік підвищення вип...
2993   300  Російські ЗМІ знайшли «чергове дно» в українсь...

[2994 rows x 2 columns]

In [3]:
# drop useless column

df = df.drop(columns=['page'])

In [4]:
# drop whitespaces in the beginning of the text

df['text'] = df['text'].str.strip()

In [5]:
# drop rows that dont start with specified prefixes

prefixes = [
    'Відеофейк: ', 
    'Фейк: ', 
    'Маніпуляція: ', 
    'Фотофейк: '
]
df = df[df['text'].apply(lambda x: any(x.startswith(prefix) for prefix in prefixes))]

In [6]:
# drop those prefixes from the text

for prefix in prefixes:  
    df.loc[:, 'text'] = df['text'].str.replace(prefix, '', regex=False)

In [7]:
# add the 'label' column

df['label'] = False

In [8]:
df

                                                   text  label
0     Український військовий підірвався під час трен...  False
1     Росіянин шкодує, що отримав громадянство Украї...  False
2     Розслідування Bellingcat довело, що Єрмак запл...  False
3     Український банк пригрозив «ухилянтам» обмежен...  False
4            Українські військові залишаться без виплат  False
...                                                 ...    ...
2988             В Україні почалася епідемія гепатиту А  False
2989  український прикордонник на КПП “Станиця Луган...  False
2990  Євросоюз прагне поліпшити відносини з Росією —...  False
2991  Громадян України масово депортують з ЄС та Ізр...  False
2992  В Україні відклали на рік підвищення виплат ві...  False

[2223 rows x 2 columns]

In [9]:
# save formatted dataset

df.to_csv('./data-collection/data-stopfake-formatted.csv', index=False)

#### Formatting `data-voxukraine.csv`

In [10]:
# load and look through data

df = pd.read_csv('./data-collection/data-voxukraine.csv')
df

                                                   text
0     Фейки щодо системи охорони здоров’я: військові...
1     Скаржитися, а не мовчати: онкологія, як і кору...
2     ФЕЙК: Після підписання закону про мобілізацію ...
3     МАНІПУЛЯЦІЯ: На Дніпропетровщині зводять форти...
4     БЕЗПІДСТАВНО: У 2024 році сильно зменшилась до...
...                                                 ...
3175  Всі на вихід. Чи справді українці масово лишаю...
3176                              2017: Найкраще за рік
3177  Україні потрібна якісна аналітика: допомогти V...
3178  Антологія обману: що ми дізналися про брехню і...
3179  Алфавіт реформатора 2016: Яка важлива подія ро...

[3180 rows x 1 columns]

In [11]:
# drop whitespaces in the beginning of the text

df['text'] = df['text'].str.strip()

In [12]:
# drop useless ending from text

df.loc[:, 'text'] = df['text'].str.replace(r'\s*. Випуск №\d+$', '', regex=True)

In [13]:
# drop rows that dont start with specified prefixes

prefixes = [
    'ФЕЙК: ', 
    'МАНІПУЛЯЦІЯ: ', 
    'БЕЗПІДСТАВНО: ', 
    'НЕПРАВДА: ', 
    'КОНСПІРОЛОГІЯ: ', 
    'ВІДЕОФЕЙК: ', 
    'САТИРА: ', 
    'ФОТОФЕЙК: ', 
    'Фейки щодо системи охорони здоров’я: '
]
df = df[df['text'].apply(lambda x: any(x.startswith(prefix) for prefix in prefixes))]

In [14]:
# drop those prefixes from the text

for prefix in prefixes:  
    df.loc[:, 'text'] = df['text'].str.replace(prefix, '', regex=False)

In [15]:
# add the 'label' column

df['label'] = False

/tmp/ipykernel_54499/1761821248.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = False

In [16]:
df

                                                   text  label
0      військові ЗСУ переховуються у київських лікарнях  False
2     Після підписання закону про мобілізацію різко ...  False
3     На Дніпропетровщині зводять фортифікації, бо У...  False
4     У 2024 році сильно зменшилась допомога бригада...  False
5     ТЦК оголошує про евакуацію з Краматорська та С...  False
...                                                 ...    ...
3057  Вчені розробили пластир, який будуть вживлюват...  False
3058  Замість невакцинованих медиків у Нью-Йорку до ...  False
3060  У вакцинах від Moderna і Jonson&Jonson виявили...  False
3061  У Ватикані у третьому читанні прийняли поправк...  False
3123  Італійські вчені протестували ківі на COVID-19...  False

[2882 rows x 2 columns]

In [17]:
# save formatted dataset

df.to_csv('./data-collection/data-voxukraine-formatted.csv', index=False)

#### Formatting `data-kaggle.csv`

In [18]:
df = pd.read_csv('./data-collection/data-kaggle.csv')

In [19]:
df

,Unnamed: 0,Link,Text,Label
0,0,https://t.me/c/1376264484/328,"Просто слухайте цей діалог. Ні, це не нарізка ...",True
1,1,https://t.me/c/1376264484/338,️ Рубль став найнестабільнішою валютою у всьом...,True
2,2,https://t.me/c/1376264484/350,Перше звернення мера Мелітополя Івана Федорова...,True
3,3,https://t.me/c/1376264484/361,"Росія загрожує Боснії ""українським сценарієм"" ...",True
4,4,https://t.me/c/1376264484/366,"Енергоатом повідомив, що окупанти пошкодили ви...",True
...,...,...,...,...
17730,19272,NaN,"""Хочуть ""подарувати"" Донбас Путіну до Пасхи""....",True
17731,22692,NaN,Сьогодні на місцевому ринку у Миколаєві один ...,True
17732,35708,NaN,"В ніч проти неділі, 11 вересня, російська оку...",True
17733,49801,NaN,"️Служба безпеки України склала памятку про те,...",True
17734,25734,NaN,З’явилися фото з місця падіння збитої ракети н...,True

In [20]:
# drop texts from the source that has already been used

df = df[df['Link'] != 'https://voxukraine.org/category/voks-informue/']

In [21]:
# drop useless columns

df = df.drop(columns=['Unnamed: 0', 'Link'])

In [22]:
# rename columns

df = df.rename(columns={'Text': 'text', 'Label': 'label'})

In [23]:
# remove colons from the beginning of some texts

df['text'] = df['text'].str.lstrip(': ')

In [24]:
df

                                                    text  label
0      Просто слухайте цей діалог. Ні, це не нарізка ...   True
1      ️ Рубль став найнестабільнішою валютою у всьом...   True
2      Перше звернення мера Мелітополя Івана Федорова...   True
3      Росія загрожує Боснії "українським сценарієм" ...   True
4      Енергоатом повідомив, що окупанти пошкодили ви...   True
...                                                  ...    ...
17730  "Хочуть "подарувати" Донбас Путіну до Пасхи". ...   True
17731  Сьогодні на місцевому ринку у Миколаєві один з...   True
17732  В ніч проти неділі, 11 вересня, російська окуп...   True
17733  ️Служба безпеки України склала памятку про те,...   True
17734  З’явилися фото з місця падіння збитої ракети н...   True

[17513 rows x 2 columns]

In [25]:
# save formatted dataset

df.to_csv('./data-collection/data-kaggle-formatted.csv', index=False)

#### Merging 3 datasets (`data-stopfake.csv`, `data-voxukraine.csv`, `data-kaggle.csv`)

In [26]:
# load all datasets

df1 = pd.read_csv('./data-collection/data-stopfake-formatted.csv')
df2 = pd.read_csv('./data-collection/data-voxukraine-formatted.csv')
df3 = pd.read_csv('./data-collection/data-kaggle-formatted.csv')

In [27]:
# merge datasets

df = pd.concat([df1, df2, df3])
df = df.reset_index(drop=True)

In [28]:
df

                                                    text  label
0      Український військовий підірвався під час трен...  False
1      Росіянин шкодує, що отримав громадянство Украї...  False
2      Розслідування Bellingcat довело, що Єрмак запл...  False
3      Український банк пригрозив «ухилянтам» обмежен...  False
4             Українські військові залишаться без виплат  False
...                                                  ...    ...
22613  "Хочуть "подарувати" Донбас Путіну до Пасхи". ...   True
22614  Сьогодні на місцевому ринку у Миколаєві один з...   True
22615  В ніч проти неділі, 11 вересня, російська окуп...   True
22616  ️Служба безпеки України склала памятку про те,...   True
22617  З’явилися фото з місця падіння збитої ракети н...   True

[22618 rows x 2 columns]

In [29]:
# check the true/false news ratio

f'True: {len(df[df["label"] == True])}, False: {len(df[df["label"] == False])}'

'True: 15237, False: 7381'

In [30]:
# save the final dataset

df.to_csv('./data-collection/data.csv', index=False)

In [31]:
# import random

# df1 = pd.read_csv('data_set_4.csv')
# df2 = pd.read_csv('news_data.csv')

# df2 = df2[df2['Label'] != False]

# text_values_df1 = set(df1['Text'])
# df2 = df2[~df2['Text'].isin(text_values_df1)]

# random_indices = random.sample(range(len(df2)), 7000)
# random_rows_df2 = df2.iloc[random_indices]
# df1 = pd.concat([df1, random_rows_df2], ignore_index=True)

# df1.to_csv('./data-collection/data-kaggle.csv', index=False)